flags: {}
packages:
- location: .
- location:
    git: https://github.com/stschiff/sequence-formats.git
    commit: b90cd7a6c9b461be863168a5b008663927c6f97b
  extra-dep: true
extra-deps: []
resolver: lts-10.5
