flags: {}
packages:
- location: .
- location:
    git: https://github.com/stschiff/sequence-formats.git
    commit: ae78f2b94a63291a8ab3358b6520923c68e76aff
  extra-dep: true
extra-deps: []
resolver: lts-10.5
