flags: {}
packages:
- location: .
- location:
    git: https://github.com/stschiff/sequence-formats.git
    commit: a44d607e96fb230739613d28a95d89c208f53f76
  extra-dep: true
extra-deps: []
resolver: lts-10.5
