flags: {}
packages:
- location: .
- location:
    git: https://github.com/stschiff/sequence-formats.git
    commit: 9991eeaa789b463ac3766a46c9def03575fb79fb
  extra-dep: true
extra-deps: []
resolver: lts-10.5
