flags: {}
packages:
- location: .
- location:
    git: https://github.com/stschiff/sequence-formats.git
    commit: 39b094cc81ab4da23a4736202dc91965048f405e
  extra-dep: true
extra-deps: []
resolver: lts-10.5
